---

- name: Set facts for golang
  ansible.builtin.set_fact:
    go_path: "/usr/local/go/bin/go"
    go_root: "$HOME/go"
    path: "PATH=$GOPATH/bin:$GOROOT/bin:$PATH"
    jb_path: "/root/go/bin/jb"
    jsonnet_path: "/root/go/bin/jsonnet"
  tags: go

- name: Copy kubeconfig to local machine
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/{{ inventory_hostname }}-config
    flat: true
  tags: kubeconfig

- name: Set kubeconfig location
  ansible.builtin.set_fact:
    kubeconfig: ~/.kube/{{ inventory_hostname }}-config
  changed_when: false
  tags:
    - kubeconfig
    - prom_install

- name: Add nginx stable chart repo
  kubernetes.core.helm_repository:
    name: nginx-stable
    repo_url: "https://helm.nginx.com/stable"
  tags: helm_update

- name: Update the Helm repository cache
  kubernetes.core.helm:
    name: nginx-ingress
    namespace: "{{ kube_namespace }}"
    chart_ref: nginx-stable/nginx-ingress
    state: present
    update_repo_cache: true
  tags: helm_update

- name: Test for existing namespace {{ kube_namespace }}
  ansible.builtin.command: kubectl get ns
  register: namespace_test
  changed_when: false
  tags:
    - namespace

- name: Create namespace {{ kube_namespace }}
  ansible.builtin.command: kubectl create ns {{ kube_namespace }}
  when: "kube_namespace not in namespace_test.stdout"
  tags: namespace

- name: Test if NginX is already installed
  ansible.builtin.shell:
    cmd: |
      helm list -n {{ kube_namespace }} | grep nginx
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc >= 2
  tags: namespace

- name: Install NginX
  ansible.builtin.command:
    helm install ingress-nginx ingress-nginx/ingress-nginx --namespace {{ kube_namespace }}
  when: "'nginx' not in nginx_test.stdout"
  tags: namespace

- name: Clone kube-prometheus repo
  ansible.builtin.git:
    repo: 'https://github.com/prometheus-operator/kube-prometheus.git'
    dest: "{{ prometheus_bin }}"
    version: "{{ release_tag }}"
  tags: git

# Customize Kube-Prometheus
- name: Make directory for Go packages
  ansible.builtin.file:
    path: "{{ go_root }}/bin"
    state: directory
    mode: '644'

- name: Check for existing Go packages
  ansible.builtin.command: "ls {{ go_root }}/bin"
  register: go_binaries
  changed_when: false

- name: Install Jsonnet-bundler
  ansible.builtin.command:
    "{{ go_path }} get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb"
  when: "'jb' not in go_binaries.stdout"

- name: Install gojasontoyaml
  ansible.builtin.command:
    "{{ go_path }} get github.com/brancz/gojsontoyaml"
  when: "'gojsontoyaml' not in go_binaries.stdout"

- name: Install go-jsonett
  ansible.builtin.command:
    "{{ go_path }} get github.com/google/go-jsonnet/cmd/jsonnet"
  when: "'jsonnet' not in go_binaries.stdout"

- name: Test for existing my-kube-prometheus directory
  ansible.builtin.stat:
    path: "{{ prometheus_bin }}/my-kube-prometheus"
  register: directory_created

- name: Create directory for customized kube-prometheus
  ansible.builtin.file:
    path: "{{ prometheus_bin }}/my-kube-prometheus"
    mode: '644'
    state: directory
  register: mydir
  when: not directory_created.stat.exists

- name: Check for existing jsonnetfile.json file
  ansible.builtin.stat:
    path: "{{ prometheus_bin }}/my-kube-prometheus/jsonnetfile.json"
  register: jsonnetfile_created

- name: Initialize the jsonnetfile.json file
  ansible.builtin.command:
    "{{ jb_path }} init"
  args:
    chdir: "{{ prometheus_bin }}/my-kube-prometheus"
  register: cmd_result
  when: not jsonnetfile_created.stat.exists

- name: Get directory contents for my-kube-prometheus
  ansible.builtin.command:
    ls {{ prometheus_bin }}/my-kube-prometheus
  register: kube_dir_contents
  changed_when: false

- name: Create "vendor" content
  ansible.builtin.command:
    "{{ jb_path }} install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@{{ jb_release }}"
  args:
    chdir: "{{ prometheus_bin }}/my-kube-prometheus"
  register: cmd_result
  when: "'vendor' not in kube_dir_contents.stdout"

- name: Download example.json file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/{{ jb_release }}/example.jsonnet
    dest: "{{ prometheus_bin }}/my-kube-prometheus/example.jsonnet"
    mode: '644'
  when: "'example.jsonnet' not in kube_dir_contents.stdout"

- name: Check for existing build.sh script
  ansible.builtin.stat:
    path: "{{ prometheus_bin }}/my-kube-prometheus/build.sh"
  register: build_exists
  changed_when: false

- name: Download build.sh file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/{{ jb_release }}/build.sh
    dest: "{{ prometheus_bin }}/my-kube-prometheus/build.sh"
    mode: '644'
  when: "'build.sh' not in kube_dir_contents.stdout"
  register: build_script

- name: Make build.sh executable
  ansible.builtin.file:
    dest: "{{ prometheus_bin }}/my-kube-prometheus/build.sh"
    mode: +x

# Add PVC to Prometheus pods
- name: Customize the Prometheus configuration
  ansible.builtin.blockinfile:
    path: "{{ prometheus_bin }}/my-kube-prometheus/example.jsonnet"
    block: |2
          prometheus+:: {
            prometheus+: {
              spec+: {
                retention: '30d',
                storage: {
                  volumeClaimTemplate: {
                    apiVersion: 'v1',
                    kind: 'PersistentVolumeClaim',
                    spec: {
                      accessModes: ['ReadWriteOnce'],
                      resources: { requests: { storage: '100Gi' } },
                      storageClassName: '{{ storage_class | default("nebulon-mirrored") }}',
                    },
                  },
                },  // storage
              },  // spec
            },  // prometheus
          },  // prometheus
    insertafter: "},"
  tags: insert

# Customize the manifests for our needs

- name: Check for existing manifests folder
  ansible.builtin.stat:
    path: "{{ prometheus_bin }}/my-kube-prometheus/manifests"
  register: manifests_created

- name: Build custom manifests
  ansible.builtin.command:
    "./build.sh example.jsonnet"
  args:
    chdir: "{{ prometheus_bin }}/my-kube-prometheus"
  environment:
    PATH: /root/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: not manifests_created.stat.exists

- name: Check for 0namespace file
  ansible.builtin.command:
    ls {{ prometheus_bin }}/my-kube-prometheus/manifests/setup
  register: dir_test
  changed_when: false

- name: Remove the default namespace manifest
  ansible.builtin.file:
    path: "{{ prometheus_bin }}/my-kube-prometheus/manifests/setup/0namespace-namespace.yaml"
    state: absent
  when: "'0namespace-namespace.yaml' in dir_test.stdout"

- name: Modify grafana-service.yaml file
  ansible.builtin.blockinfile:
    path: "{{ prometheus_bin }}/my-kube-prometheus/manifests/grafana-service.yaml"
    block: |2
        type: LoadBalancer
    insertafter: "app: grafana"

- name: Modify prometheus-service.yaml file
  ansible.builtin.blockinfile:
    path: "{{ prometheus_bin }}/my-kube-prometheus/manifests/prometheus-service.yaml"
    block: |2
        type: LoadBalancer
    insertafter: "sessionAffinity: ClientIP"

- name: Modify prometheus-prometheus.yaml file (remove content)
  ansible.builtin.lineinfile:
    path: "{{ prometheus_bin }}/my-kube-prometheus/manifests/prometheus-prometheus.yaml"
    regexp: "{{ item.regexp }}"
    state: absent
  with_items:
    - { regexp: 'fsGroup:'}
    - { regexp: 'runAsNonRoot'}
    - { regexp: 'runAsUser'}
  tags: customize

# I need to fix this as its a security concern
- name: Modify prometheus-prometheus.yaml file (add content)
  ansible.builtin.blockinfile:
    path: "{{ prometheus_bin }}/my-kube-prometheus/manifests/prometheus-prometheus.yaml"
    block: |2
          fsGroup: 65534
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
    insertafter: "securityContext"
  tags: customize

# Install the customizes manifests

- name: Create the namespace and CRDs
  ansible.builtin.command: kubectl create -f {{ prometheus_bin }}/my-kube-prometheus/manifests/setup
  register: kubectl_output
  failed_when: kubectl_output.rc > 1
  changed_when: "'AlreadyExists' not in kubectl_output.stderr"
  tags:
    - prom_install

- name: Wait for CRDs to be available
  ansible.builtin.shell:
    kubectl get customresourcedefinition {{ item }}.monitoring.coreos.com > /dev/null 2>&1
  register: crd_check
  until: crd_check.rc == 0
  retries: 30
  delay: 1
  with_items:
    - servicemonitors
    - prometheuses
    - alertmanagers
  changed_when: false
  tags:
    - prom_install

- name: Install remaining kube-prometheus manifests
  ansible.builtin.command:
    kubectl create -f {{ prometheus_bin }}/my-kube-prometheus/manifests/
  register: kubectl_output
  failed_when: kubectl_output.rc > 1
  changed_when: "'AlreadyExists' not in kubectl_output.stderr"
  tags:
    - prom_install
